### ISSUE TITLE
PRnetTrainer' object has no attribute 'r2_mean

### ISSUE THREAD

**Issue by ehdhssh** [Perturbation-Response-Prediction/PRnet#1]
When I run `python test_demo.py --split_key demo_split --data_path /mnt/e/PRnet/dataset/demo.h5ad --results_dir /mnt/e/PRnet/results`, I encounter the error "AttributeError: 'PRnetTrainer' object has no attribute 'r2_mean'." How can I resolve this issue? Thank you.

**Comment by younng367** [comment]
did you solve it? i also met the same erro

**Comment by Jianbo1999** [comment]
I also met this bug

**Comment by olarerin-lab** [comment]
I am also having the same problem an can't get past the demo.  Any help appreciated.

**Comment by nicole1q** [comment]
We have recently updated the GitHub repository to address some missing functions in the code. Please pull the latest version, which should resolve these issues.
