### ISSUE TITLE
Lack of "drug_split_0_y_true_array.csv" while analysising the results

### ISSUE THREAD

**Issue by Awarxyz** [Perturbation-Response-Prediction/PRnet#10]
Hi, at the end of Step 4: train and test with provided datatset, I get three files: drug_split_0_cov_drug_array.csv, drug_split_0_x_true_array.csv and drug_split_0_y_pre_array.csv, but in Step 5, file "analysis_sciplex.py", line 45,
`true_array = np.genfromtxt(config_kwargs['save_dir']+config_kwargs['split_key']+'_y_true_array.csv', delimiter=',')`
It seems that the file 'drug_split_0_y_true_array.csv' is also needed, how should I deal with it？Any help is appreciated.

**Comment by nicole1q** [comment]
To generate the y_true_array, you can modify the PRnetTrainer.test function as follows:

Add the Code:
Inside the PRnetTrainer.test function, include the following lines to save the true labels (y_true_array) during the test process:

‘’‘
y_true = target.cpu().numpy()
y_true_array = np.concatenate((y_true_array, y_true), axis=0)
with open(self.results_save_dir + self.split_key + "_y_true_array.csv", 'a+') as f:
    np.savetxt(f, y_true, delimiter=",")
‘’’
This will write the y_true_array to a file named drug_split_0_y_true_array.csv (or the corresponding split key) in the same directory as your other result files.

**Comment by Awarxyz** [comment]
> To generate the y_true_array, you can modify the PRnetTrainer.test function as follows:
> 
> Add the Code: Inside the PRnetTrainer.test function, include the following lines to save the true labels (y_true_array) during the test process:
> 
> ‘’‘ y_true = target.cpu().numpy() y_true_array = np.concatenate((y_true_array, y_true), axis=0) with open(self.results_save_dir + self.split_key + "_y_true_array.csv", 'a+') as f: np.savetxt(f, y_true, delimiter=",") ‘’’ This will write the y_true_array to a file named drug_split_0_y_true_array.csv (or the corresponding split key) in the same directory as your other result files.

I do as you said and It works! Thank you very much!
