### ISSUE TITLE
关于GSE92742中landmark基因 

### ISSUE THREAD

**Issue by Zoeyk9** [Perturbation-Response-Prediction/PRnet#11]
你好，请问项目中使用的是Level 3 级别的原始LINCS数据吗？我在GSE92742_Broad_LINCS_Level3_INF_mlr12k_n1319138x12328.gctx.gz文件中只提取到977个landmark基因，编号为10929的基因SRSF8好像没有出现在原始文件中。请问您在构建数据集时遇到这个问题了吗？

**Comment by prsigma** [comment]
你好 请问问题解决了吗 我用这个landmark基因也只有977个
