### ISSUE TITLE
about r2_mean issue 

### ISSUE THREAD

**Issue by younng367** [Perturbation-Response-Prediction/PRnet#2]
guys you have to add the two function by manual .which in the data fold. r2_mean and pearson_mean

**Comment by Jianbo1999** [comment]
can you say more details? Please

**Comment by Jianbo1999** [comment]
I added this codes in line 510, it work.

def pearson_mean(data1, data2):
    sum_pearson_1 = 0
    sum_pearson_2 = 0
    for i in range(data1.shape[0]):
        pearsonr_ = pearsonr(data1[i], data2[i])
        sum_pearson_1 += pearsonr_[0]
        sum_pearson_2 += pearsonr_[1]
    return sum_pearson_1/data1.shape[0], sum_pearson_2/data1.shape[0]

def r2_mean(data1, data2):
    sum_r2_1 = 0
    for i in range(data1.shape[0]):
        r2_score_ = r2_score(data1[i], data2[i])
        sum_r2_1 += r2_score_           
    return sum_r2_1/data1.shape[0]

**Comment by nicole1q** [comment]
We have recently updated the GitHub repository to address some missing functions in the code. Please pull the latest version, which should resolve these issues.
