### ISSUE TITLE
lack of dataset file

### ISSUE THREAD

**Issue by younng367** [Perturbation-Response-Prediction/PRnet#3]
could you upload the dataset file?Please~~~~~ Dear professor

**Comment by nicole1q** [comment]
If the links fail to redirect, please download the corresponding data and pretrained model weights from: http://prnet.drai.cn/Statistics/. For the data files, download LINCS L1000 Chemical Perturbations and Sci-plex Chemical Perturbations from the Supplementary Dataset section. For the model weights, download the PRnet model from the Supplementary Dataset section.

**Comment by Jianbo1999** [comment]
Hello, where is the data: FDA_drug_fold-change_2W.csv

**Comment by nicole1q** [comment]
> If the links fail to redirect, please download the corresponding data and pretrained model weights from: http://prnet.drai.cn/Statistics/. For the data files, download LINCS L1000 Chemical Perturbations and Sci-plex Chemical Perturbations from the Supplementary Dataset section. For the model weights, download the PRnet model from the Supplementary Dataset section.  Then change the names of the datasets to `Lincs_L1000.h5ad` and `Sci_Plex.h5ad` respectively. If the dataset cannot be downloaded, please adjust your browser settings to allow insecure content on the current webpage by setting it to "Allow."

**Comment by Jianbo1999** [comment]
I would like to find a similar molecule to my small molecule (I had transcriptomics data) using the PRnet. How can I do it?

**Comment by nicole1q** [comment]
> Hello, where is the data: FDA_drug_fold-change_2W.csv

 Please download the corresponding data from: http://prnet.drai.cn/Statistics/.  ‘FDA_drug_fold-change_2W.csv’:  download the FDA-approved Drugs Signatures from the PRnet Predicted Transcriptional Signatures section.

**Comment by nicole1q** [comment]
> I would like to find a similar molecule to my small molecule (I had transcriptomics data) using the PRnet. How can I do it?

I don't quite understand, could you describe it in more detail?

**Comment by Jianbo1999** [comment]
> > I would like to find a similar molecule to my small molecule (I had transcriptomics data) using the PRnet. How can I do it?
> 
> I don't quite understand, could you describe it in more detail?

I have transcriptome and structural data of a small molecule, and I want to find similar molecules for target screening using the PRnet method

**Comment by nicole1q** [comment]
> > > I would like to find a similar molecule to my small molecule (I had transcriptomics data) using the PRnet. How can I do it?
> > 
> > 
> > I don't quite understand, could you describe it in more detail?
> 
> I have transcriptome and structural data of a small molecule, and I want to find similar molecules for target screening using the PRnet method

To prepare your dataset for a new small molecule, please refer to the instructions in [custom_data_preprocessing.ipynb](https://github.com/Perturbation-Response-Prediction/PRnet/blob/main/preprocessing/custom_data_preprocessing.ipynb). Once your dataset is ready, you can predict the perturbed expression profile by running test_demo.py, adjusting the split_key argument as needed for your analysis.

If you’re interested in other applications or discussing potential collaborations, please feel free to reach out at [biozy@ict.ac.cn](mailto:biozy@ict.ac.cn).
