### ISSUE TITLE
一个数据处理问题

### ISSUE THREAD

**Issue by ZexiChen502** [Perturbation-Response-Prediction/PRnet#4]
观察代码的时候产生了疑问，lincs或单细胞数据中，扰动前后应该是无法配对的。那么代码中的扰动后细胞的obs.paired_control_index(扰动前对应的细胞索引）是在数据处理时候随机赋予的吗？

**Comment by nicole1q** [comment]
是的，考虑到技术原因lincs或单细胞数据中扰动前后应该是无法配对的，所以将每个扰动后的表达谱随机赋予了一个同细胞系或细胞类型的表达谱做配对，预测时预测扰动后的分布情况（详见文章Methods部分）
