### ISSUE TITLE
数据下载困难-http://prnet.drai.cn/Statistics/

### ISSUE THREAD

**Issue by bluesea2018** [Perturbation-Response-Prediction/PRnet#6]
您好
    http://prnet.drai.cn/Statistics/这里的数据下载困难，能否麻烦传到网盘里？谢谢

**Comment by nicole1q** [comment]
The links above are temporarily unavailable due to bandwidth limitations. Please download the corresponding data from [![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.14033163.svg)](https://zenodo.org/doi/10.5281/zenodo.14033163).

**Comment by bluesea2018** [comment]
Thanks

**Comment by bluesea2018** [comment]
您好
   能不能把http://prnet.drai.cn/Statistics/这里其它的可下载的也上传到这里https://zenodo.org/doi/10.5281/zenodo.14033163，
